name: steel_alert
description: "Steel Alert is a Flutter package that provides a simple way to show alerts in your app."
version: 0.0.3
homepage: https://github.com/melihcelik09/steel_alert

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
